city = input("Where do you want to go?")
distantion = int(input("How long your distantion? please give me ansver in km"))
vmid = int(input("What is the middle speed of the car?")) 
costgas = int(input("How much cost one liter of gasoline?"))
usegas = int(input("How much gasoline use for 100km?"))
timetrip = (distantion/vmid)
gastrip = (distantion/usegas)
costtrip = (gastrip*costgas*100)
resulttime = (round(timetrip, 2))
resultgas = (round(gastrip, 2))
resultcost = (round(costgas, 2))
print("Time for trip =", resulttime,"hours")
print("You need", resultgas, "liters of gasoline")
print("You need", resultcost, "uan for this trip")